name: Linux build images
on:
    push:
        paths:
            - docker/linux.Dockerfile
            - cmake/ports/**
            - hifi_qt.py
jobs:
    build-and-push-to-registry:
        name: Build and push to registry
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@v2

            - name: Login to ghcr.io
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v1
              with:
                  platforms: arm64

            - name: Setup Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push Docker images
              uses: docker/build-push-action@v2
              with:
                  context: docker
                  file: docker/linux.Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/tivolicloud/build:linux
